version: '3.7'
services:
    nginx:
        container_name: nginx
        image: nginx:mouad
        build:
            context: requirements/nginx
            dockerfile: Dockerfile
        volumes:
            - wordpress:/var/www/html
        networks: 
            - inception
        ports:
            - 443:443
        restart: unless-stopped
        depends_on: 
            - wordpress

    mariadb:
        container_name: mariadb
        image: mariadb:mouad
        build:
            context: requirements/mariadb
            dockerfile: Dockerfile
        volumes:
            - mariadb:/var/lib/mysql
        networks: 
            - inception
        restart: unless-stopped
        env_file: .env

    wordpress:
        container_name: wordpress
        image: wordpress:mouad
        build:
            context: requirements/wordpress
            dockerfile: Dockerfile
        volumes:
            - wordpress:/var/www/html
        networks: 
            - inception
        restart: unless-stopped
        depends_on: 
            - mariadb
        env_file: .env
    
volumes:
    wordpress:
        name: wordpress
        driver: local
        driver_opts:
            type: "none"
            device: "/home/mouaammo/data/wordpress"
            o: "bind"
    mariadb:
        name: mariadb
        driver: local
        driver_opts:
            type: "none"
            device: "/home/mouaammo/data/mariadb"
            o: "bind"
networks:
    inception:
        driver: bridge
        name: inception